[emojiMap]
lul = ""
roflanZdarova = ""
mc_fox = ""
pepeGlass = ""
kPogYOU = ""
kotochih_deal = ""
troll2 = ""
mc_cat = ""
upvote = ""
horosh = ""
kPogU = ""
pepejuice = ""
kPogChamp = ""
teacis = ""
nugget_sad = ""
mSeriously = ""
skyfrown = ""
pepeLove = ""
flag_yasenevo = ""
pepeShrug = ""
flag_barnaul = ""
poggers = ""
eXO = ""
pepeEw = ""
kGod = ""
gryznya = ""
hollow = ""
nugget_happy = ""
kPissedChamp = ""
socool = ""
pepe_troll = ""
pepeSadge = ""
eThonk = ""
orehus = ""
flag_krasnodar = ""
flag_kazan = ""
Kekw = ""
pepeJoker = ""
kMadChamp = ""
clueless = ""
eSunglss = ""
blooshed = ""
wazowski = ""
bte = ""
eHz = ""
cisLOGO = ""
flag_tuapse = ""
wut = ""
sopro = ""
kWeirdPog = ""
pepe_flushed = ""
think = ""
flag_spb = ""
flag_moscow = ""
pepeBan = ""
eGrr = ""
vlad = ""
kPainsChamp = ""
pepeNoted = ""
pepe_happy = ""
pepeCross = ""
klim = ""
kotochih_facepalm = ""
pepe_toast = ""
kTrollChamp = ""
pepeBased = ""
cursed = ""
LookingMonkey = ""
eVibe = ""
YellingWoman = ""
kotochih = ""
ladno = ""
kWhatchamp = ""
doggo = ""
renard = ""
kotochih_dang = ""
pepeDumb = ""
pepeclownsad = ""
flag_su = ""
aightcool = ""
mm = ""
pSadgee = ""
flag_nagatynsky = ""
kPogMega = ""
flag_yakutia = ""
pepeHands = ""
pmonkaS = ""
facepalm = ""
pepeHappy = ""
pepePray = ""
patreon = ""
kKekwChamp = ""
durka = ""
eSmil = ""
pepeAngry = ""
vk = ""
whygod = ""
pepeCringe = ""
stonks = ""
kPauseChamp = ""
troll_pause = ""
eWena = ""
pingsock = ""
reznya = ""
feelswowman = ""
pepeLaugh = ""
NO = ""
pepe_popcorn = ""
pepeKavun = ""
pepecool = ""
w_ = ""
kSadChamp = ""
gruno = ""
forbid = ""
LookingFish = ""
bruh = ""
pmonkaGIGA = ""
kWeirdChamp = ""
kotochih_thumbsup = ""
kpog = ""
kHappyChamp = ""
volk = ""
perhaps = ""
ok1 = ""
BONK = ""
eNice = ""
F_ = ""
pepeclownchad = ""
kOmegaPog = ""
pain = ""
roflan = ""
pepega = ""
yes = ""
pepethink = ""
kPain = ""
eNooWhyyy = ""
eTipHat = ""
trol = ""
yoba = ""
shocked = ""
pepeClownToxic = ""
NotStonks = ""
flag_zelenograd = ""
roflanPominki = ""
pepe_ok = ""
